export const timeTable = [
  {
    date: "24 March",
    day: "Fri",
    ramadan: "01",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ke Sath Ishq-E-Mustafa Naseeb Farma.",
  },
  {
    date: "25 March",
    day: "Sat",
    ramadan: "02",
    sehri: "4:55",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Ikhlas Wale Aamal Naseeb Farma Aur  Tere Mehboob Ki Sunnato Par Chala.",
  },
  {
    date: "26 March",
    day: "Sun",
    ramadan: "03",
    sehri: "4:55",
    iftar: "6:31",
    dua: "Ae Allah Maut Tak Mere Imaan ki Hifazat Farma.",
  },
  {
    date: "27 March",
    day: "Mon",
    ramadan: "04",
    sehri: "4:53",
    iftar: "6:32",
    dua: "Ae Allah Naza Ke Waqt Zuban Par Kalmaye Tayyaba Aur Ankho Me Tere Mehboob Ki Ziyarat Naseeb Farma.",
  },
  {
    date: "28 March",
    day: "Tue",
    ramadan: "05",
    sehri: "4:53",
    iftar: "6:32",
    dua: "Ae Allah Ramzan Mubarak Ki Naimato se aur iske Fyuz o Barkat se Malamal Farma.",
  },
  {
    date: "29 March",
    day: "Wed",
    ramadan: "06",
    sehri: "4:51",
    iftar: "6:32",
    dua: "Ae Allah Mujhe Hiadayat-E-Kamil Naseeb Farma Farma.",
  },
  {
    date: "30 March",
    day: "Thu",
    ramadan: "07",
    sehri: "4:51",
    iftar: "6:32",
    dua: "Ae Allah Teri Raza Aur Khushnadi Wali Zindagi Ata Farma.",
  },
  {
    date: "31 March",
    day: "Fri",
    ramadan: "08",
    sehri: "4:51",
    iftar: "6:32",
    dua: "Ae Allah Zinadagi Me Sahi Namaz Ada Karne Ki Taufeeq Ata Farma.",
  },
  {
    date: "1 April",
    day: "Sat",
    ramadan: "09",
    sehri: "4:48",
    iftar: "6:33",
    dua: "Ae Allah Huzur-E-Akram(S.A.W) Ki Tamam Sunnato Par Amal Karne ki Taufiq  Ata Farma.",
  },
  {
    date: "2 April",
    day: "Sun",
    ramadan: "10",
    sehri: "4:48",
    iftar: "6:33",
    dua: "Ae Allah Hamari Roze Jaisi Ibadat Ko Darja e Maqbuliyat Ata Farma.",
  },
  {
    date: "3 April",
    day: "Mon",
    ramadan: "11",
    sehri: "4:46",
    iftar: "6:34",
    dua: "Ae Allah Badbakhti Aur Tangdasti Se Hamari Hifazat Ata Farma.",
  },
  {
    date: "4 April",
    day: "Tue",
    ramadan: "12",
    sehri: "4:46",
    iftar: "6:34",
    dua: "Ae Allah Jhut, Gibat, Kina, Takabbur aur Tamam Shaitani Amal Se Hamari Hifazat Farma.",
  },
  {
    date: "5 April",
    day: "Wed",
    ramadan: "13",
    sehri: "4:44",
    iftar: "6:35",
    dua: "Ae Allah Shaitan Aur Nafs se Hamari Hifazat Farma.",
  },
  {
    date: "6 April",
    day: "Thu",
    ramadan: "14",
    sehri: "4:44",
    iftar: "6:35",
    dua: "Ae Allah Hamare Dil Me Aisa Yaqin Paida Kar Jiski Buniyad Namaz Aur Qalma e Taiyaba Par Ho Aur Tere Mehboob Ke Ashiqo me Hamara Shumar Ata Farma.",
  },
  {
    date: "7 April",
    day: "Fri",
    ramadan: "15",
    sehri: "4:42",
    iftar: "6:35",
    dua: "Ae Allah Hame Taqwa Aur Parhezgari Ata Farma.",
  },
  {
    date: "8 April",
    day: "Sat",
    ramadan: "16",
    sehri: "4:42",
    iftar: "6:35",
    dua: "Ae Allah Hame Duniya Aur Akherat Ki Bhalai Naseeb Farma.",
  },
  {
    date: "9 April",
    day: "Sun",
    ramadan: "17",
    sehri: "4:40",
    iftar: "6:36",
    dua: "Ae Allah Qayamat Ke Din Arsh Ka Saya Aur Tere Mehboob Ki Shafat Naseeb Farma.",
  },
  {
    date: "10 April",
    day: "Mon",
    ramadan: "18",
    sehri: "4:40",
    iftar: "6:36",
    dua: "Ae Allah Duniya Aur Akherat Ki Zillat Se Hamari Hifazat Farma.",
  },
  {
    date: "11 April",
    day: "Tue",
    ramadan: "19",
    sehri: "4:38",
    iftar: "6:37",
    dua: "Ae Allah Maali, Jismani aur Budhape ki Kamzori me Teri Makhluk Ka Mohtaj Na Bana.",
  },
  {
    date: "12 April",
    day: "Wed",
    ramadan: "20",
    sehri: "4:38",
    iftar: "6:37",
    dua: "Ae Allah Hame Walden Ka Farmabardar Bana Aur Unke Huquq Ki Adayegi Karne Ki Taufiq Ata Farma.",
  },
  {
    date: "13 April",
    day: "Thu",
    ramadan: "21",
    sehri: "4:36",
    iftar: "6:37",
    dua: "Ae Allah Aap(S.A.W) Ki Kamil Itteba Naseeb Farma Aur Unki Sunnato Par Amal Paira Farma.",
  },
  {
    date: "14 April",
    day: "Fri",
    ramadan: "22",
    sehri: "4:36",
    iftar: "6:37",
    dua: "Ae Allah Jannat Wale Noorani Aamal Zindagi Me Ata Farma.",
  },
  {
    date: "15 April",
    day: "Sat",
    ramadan: "23",
    sehri: "4:34",
    iftar: "6:38",
    dua: "Ae Allah Halal Rozi Ke Darwaze Charo Taraf Se Kholde, Rizk e Halal Me Barkat Ata Farma ",
  },
  {
    date: "16 April",
    day: "Sun",
    ramadan: "24",
    sehri: "4:34",
    iftar: "6:38",
    dua: "Ae Allah Hame Tere Pak aur Maqbool Bando Me Shamil Kar.",
  },
  {
    date: "17 April",
    day: "Mon",
    ramadan: "25",
    sehri: "4:32",
    iftar: "6:39",
    dua: "Ae Allah Hamare Wajood Ko Sab Keliye Rahmat Banade.",
  },
  {
    date: "18 April",
    day: "Tue",
    ramadan: "26",
    sehri: "4:32",
    iftar: "6:39",
    dua: "Ae Allah Teri Aur Tere Mehboob Ki Mohabbat Ko Tamam Ki Mohabbat Par Bartari Ata Farma.",
  },
  {
    date: "19 April",
    day: "Wed",
    ramadan: "27",
    sehri: "4:30",
    iftar: "6:39",
    dua: "Ae Allah Teri Magfirat Ka Noor Hamare Dilo Me Dalde.",
  },
  {
    date: "20 April",
    day: "Thu",
    ramadan: "28",
    sehri: "4:30",
    iftar: "6:39",
    dua: "Ae Allah Teri Azmat Aur Teri Badhai Hamare Dilo Me Dalde.",
  },
  {
    date: "21 April",
    day: "Fri",
    ramadan: "29",
    sehri: "4:28",
    iftar: "6:40",
    dua: "Ae Allah Deen E Islam Aur Ehle Imaan Ki Khidmat Karne Ka Sharf Hame Aur Hamare  Ghar Walo Ko Naseeb Farma.",
  },
  {
    date: "22 April",
    day: "Sat",
    ramadan: "30",
    sehri: "4:28",
    iftar: "6:40",
    dua: "Ae Allah 'La Ilaha Illallah' Ki Haqiqat Hamare Dilo Me Dalde",
  },
];
