export const timeTable = [
  {
    date: "24 March ",
    day: "Fri",
    ramadan: "01",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Naseeb Farma",
  },
  {
    date: "25 March ",
    day: "Sat",
    ramadan: "02",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Ikhlas Wale Aamal Naseeb Farma",
  },
  {
    date: "26 March ",
    day: "Sun",
    ramadan: "03",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Maut Tak Mere Imaan ki Hifazat Farma",
  },
  {
    date: "27 March ",
    day: "Mon",
    ramadan: "04",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Naza Ke Waqt Zuban Par Kalmaye Tayyaba Jaari Farma",
  },
  {
    date: "28 March ",
    day: "Tue",
    ramadan: "05",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Ramzan Mubarak Ki Naimato se aur iske Fyuz o Barkat se Malamal  Farma",
  },
  {
    date: "29 March ",
    day: "Wed",
    ramadan: "06",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Hiadayat-E-Kamil Naseeb Farma Farma",
  },
  {
    date: "30 March ",
    day: "Thu",
    ramadan: "07",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Teri Raza Aur Khushnadi Wali Zindagi Ata Farma",
  },
  {
    date: "31 March ",
    day: "Fri",
    ramadan: "08",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Zinadagi Me Sahi Namaz Ata Farma",
  },
  {
    date: "01 April",
    day: "Sat",
    ramadan: "09",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ata Farma",
  },
  {
    date: "02 April",
    day: "Sun",
    ramadan: "10",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ata Farma",
  },
  {
    date: "03 April ",
    day: "Mon",
    ramadan: "11",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Naseeb Farma",
  },
  {
    date: "04 April ",
    day: "Tue",
    ramadan: "12",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Ikhlas Wale Aamal Naseeb Farma",
  },
  {
    date: "05 April ",
    day: "Wed",
    ramadan: "13",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Maut Tak Mere Imaan ki Hifazat Farma",
  },
  {
    date: "06 April ",
    day: "Thu",
    ramadan: "14",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Naza Ke Waqt Zuban Par Kalmaye Tayyaba Jaari Farma",
  },
  {
    date: "07 April ",
    day: "Fri",
    ramadan: "15",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Ramzan Mubarak Ki Naimato se aur iske Fyuz o Barkat se Malamal  Farma",
  },
  {
    date: "08 April ",
    day: "Sat",
    ramadan: "16",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Hiadayat-E-Kamil Naseeb Farma Farma",
  },
  {
    date: "09 April ",
    day: "Sun",
    ramadan: "17",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Teri Raza Aur Khushnadi Wali Zindagi Ata Farma",
  },
  {
    date: "10 April ",
    day: "Mon",
    ramadan: "18",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Zinadagi Me Sahi Namaz Ata Farma",
  },
  {
    date: "11 April",
    day: "Tue",
    ramadan: "19",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ata Farma",
  },
  {
    date: "12 April",
    day: "Wed",
    ramadan: "20",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ata Farma",
  },
  {
    date: "13 April ",
    day: "Thu",
    ramadan: "21",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Naseeb Farma",
  },
  {
    date: "14 April ",
    day: "Fri",
    ramadan: "22",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Ikhlas Wale Aamal Naseeb Farma",
  },
  {
    date: "15 April ",
    day: "Sat",
    ramadan: "23",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Maut Tak Mere Imaan ki Hifazat Farma",
  },
  {
    date: "16 April ",
    day: "Sun",
    ramadan: "24",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Naza Ke Waqt Zuban Par Kalmaye Tayyaba Jaari Farma",
  },
  {
    date: "17 April ",
    day: "Mon",
    ramadan: "25",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Ramzan Mubarak Ki Naimato se aur iske Fyuz o Barkat se Malamal  Farma",
  },
  {
    date: "18 April ",
    day: "Tue",
    ramadan: "26",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Hiadayat-E-Kamil Naseeb Farma Farma",
  },
  {
    date: "19 April ",
    day: "Wed",
    ramadan: "27",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Teri Raza Aur Khushnadi Wali Zindagi Ata Farma",
  },
  {
    date: "20 April ",
    day: "Thu",
    ramadan: "28",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Zinadagi Me Sahi Namaz Ata Farma",
  },
  {
    date: "21 April",
    day: "Fri",
    ramadan: "29",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ata Farma",
  },
  {
    date: "22 April",
    day: "Sat",
    ramadan: "30",
    sehri: "4:57",
    iftar: "6:31",
    dua: "Ae Allah Mujhe Iman-e-Kamil Ata Farma",
  },
];
